createStaticContent: false
showDeviceProperties: true
DollarReduction:
  - 30
  - 27.5
  - 25
  - 23
  - 21
  - 20
baseRates:
  Math6-9: 23
  Science6-9: 20
  Science10-12: 22
  Math10-12: 22
  GenChem: 25
  OrgChem: 25
  Biochem: 25
  Biology: 21
  WebDev: 28
  MSO: 28
  SharePoint: 28
  PowerApp: 23
InitialStyleRules:
  h1:
    fontSize:
      - null
      - 0.33 (14pt)
  h2:
    fontSize:
      - null
      - 0.33 (11pt)
  h3:
    fontSize:
      - null
      - 0.33 (9pt)
  h4:
    fontSize:
      - null
      - 0.33 (8pt)
  '#container':
    width:
      - null
      - auto
  body:
    fontSize:
      - null
      - 0.33 (11pt)
  'table#rates':
    width:
      - null
      - auto
Aliases:
  ASSETS_PATH:
    path: '.\assets'
    missing: error
  GH_PAGES_PATH:
    path: '.\gh-pages'
    missing: create
  COMPILEDSET: '.\build\compiledset'
  SRC_PATH:
    path: '.\src'
    missing: error
  TESTING: '.\test'
Paths_Sets:
  baseCopySet:
    - source:
        dirpath: '%#ASSETS_PATH#%'
        file: '*.jpg'
      destination:
        dirpath: '%#GH_PAGES_PATH#%\img'
        file: ''
    - source:
        dirpath: '%#SRC_PATH#%'
        file: config.yaml
      destination:
        dirpath: '%#GH_PAGES_PATH#%'
        file: config.yaml
    - source:
        dirpath: '%#COMPILEDSET#%'
        file: tutor-posting.js
      destination:
        dirpath: '%#GH_PAGES_PATH#%'
        file: tutor-posting.js
  HTMLConfigData:
    HeadTags:
      scriptsSection: &scriptsSection
        marker: <!-- %%% SCRIPT %%% -->
        dom:
          - elemAttribs:
            - name: src
              value: https://cdn.jsdelivr.net/npm/js-yaml@4.1.0/dist/js-yaml.min.js
          - elemAttribs: 
            - name: src
              value: tutor-posting.js
      linksSection: &linksSection
        marker: <!-- %%% LINK %%% -->
        dom:
          - elemAttribs: 
            - name: href
              value: css/id-class.css
            - name: rel
              value: stylesheet
          - elemAttribs: 
            - name: href
              value: css/elements.css
            - name: rel
              value: stylesheet
    Files:
      HtmlReadFile: '%#SRC_PATH#%\base.html'
      HtmlWriteIndexFile: '%#GH_PAGES_PATH#%\index.html'
      HtmlWriteStaticFile: '%#GH_PAGES_PATH#%\static.html'
      TsConfigJSCompiledFilesPath: build/compiledset
  CSSfiles:
    - src:
        - '%#SRC_PATH#%\css\*.css'
      dest: '%#GH_PAGES_PATH#%\css'
  ImportExportEditFiles:
    - '%#COMPILEDSET#%\tutor-posting.js'
PowerShellTasks:
  - title: clean gh-pages directory
    action: delete
    target:
      - '%#GH_PAGES_PATH#%'
      - '%#COMPILEDSET#%'
      - '%#TESTING#%/**'
    dryrun: false
    skip: false
  - title: compile ts files
    action: run
    executable: tsc
    arguments:
      - '-p'
      - tsconfig.json
    skip: false
  - title: post-compile processing
    action: run
    executable: node
    arguments:
      - build/compiledset/tunescript.js
    skip: false
Testing:
  Dest: '%#TESTING#%'
  Files:
    # at this level, named files are path to source that will be copied to 'Dest'
    - '%#COMPILEDSET#%\tutor-posting.js'
    - name: '%#COMPILEDSET#%\tutor-posting.js.map'
      edits: 
        - '"sources":["../../src/tutor-posting.ts"]'
        - '"sources":["tutor-posting.ts"]'
    - '%#SRC_PATH#%\tutor-posting.ts'
    - '%#GH_PAGES_PATH#%\index.html'
    - '%#SRC_PATH#%\types.d.ts'
    - '%#GH_PAGES_PATH#%\config.yaml'
    - '%#GH_PAGES_PATH#%\css\id-class.css'
    - '%#GH_PAGES_PATH#%\css\elements.css'
    - '%#GH_PAGES_PATH#%\img\SMHdiploma.jpg'
