# Mulitple choice format concept

---
- question: "If a right-angled triangle has sides of length $a$ and $b$, what is the length of the hypotenuse $c$ according to the Pythagorean theorem?"
  options:
    - "a) $c = a+b$"
    - "b) $c = a^2+b^2$"
    - "c) $c = \\sqrt{a^2+b^2}$"
    - "d) $c = \\sqrt{a+b}$"
  answer: "c"
- question: "What is the result of the following expression? $$\\int_{0}^{1} x^2 \\,dx$$"
  options:
    - "a) $\\frac{1}{2}$"
    - "b) $\\frac{1}{3}$"
    - "c) $1$"
    - "d) $0$"
  answer: "b"
- question: "Which of the following describes the molecular geometry of methane, $\\text{CH}_4$?"
  options:
    - "a) Linear"
    - "b) Trigonal planar"
    - "c) Tetrahedral"
    - "d) Bent"
  answer: "c"
- question: "Find the value of $x$ in the equation $4x - 7 = 5$."
  options:
    - "a) $x=2$"
    - "b) $x=3$"
    - "c) $x=4$"
    - "d) $x=5$"
  answer: "b"
- question: "A particle moves with a velocity function $v(t) = t^2 + 2t - 1$. What is the acceleration at $t=3$?"
  options:
    - "a) $8$"
    - "b) $12$"
    - "c) $14$"
    - "d) $18$"
  answer: "a"