tail: cleaned
dirs:
  default: "D:/Mavigozler GitHub/mavigozler.github.io/TheHalloranCompleteReference"
  dir1: "D:/Mavigozler GitHub/mavigozler.github.io/TheHalloranCompleteReference"
  dir2: ""
files:
  - dir1/AcidIonizationConstants.html
  - allbiochem.html
  - AnalyticalInstruments.html
  - bioinformatics.xhtml
  - biology.html
  - BiologyFirstYear.html
  - Calculus.xhtml
  - CellCulture.html
  - constants.html
  - DogPsychologyBehaviorTraining.html
  - DrugAnalysis.html
  - EducationPage.html
  - ekginfo.html
  - GeneralChemistryLectures.html
  - GeneralLaboratoryPractice.html
  - GovRegulationsLegal.html
  - histo.html
  - immunohistochem.html
  - Immunology Reference.html
  - index.html
  - IntegrationSimpleRules.xhtml
  - IntroductoryChemistry.html
  - ise.html
  - Linear Algebra -- Lectures by Gilbert Strang.xhtml
  - LKB Rackbeta 1211 OpGuide.html
  - Mathematics.xhtml
  - Methods.html
  - MolBiol_Reports.html
  - nmr-mri.html
  - OligoSynthesis.html
  - OrganicChemistry-Morrison&Boyd-METULectures.html
  - OtherMethods.html
  - PEP_CHEM.htm
  - physiology.html
  - PlantBiochemisty-METU Lectures.html
  - ProjectManagementPrinciples.html
  - proteinSequences.html
  - QuantitativePractice.html
  - recipes.html
  - SISAKnowledgebase.html
  - SoftwareProjectManagement (2).html
  - SoftwareProjectManagement.html
  - Stem Cell Biology Literature.html
  - Toxicology.html
  - UrinaryIodineMeasurementMethods.html
  - wine.html
  - xrayxtal.html
  - Zoology-METU Lectures.html